spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebookingapp
    username: root
    password: Rootsql1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: d87485aa69a356dd711c526a0fdffc8c9e8fc1136dbd5577ad4de089288e9267
  expiration: 3600000

